AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Obtém todas as filas cadastradas do usuário logado, se houver id, traz apenas
  um item
Resources:
  getqueuecustomer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: >-
        Obtém todas as filas cadastradas do usuário logado, se houver id, traz
        apenas um item
      MemorySize: 128
      Timeout: 3
      Role: ''
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /queue
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: '/queue/{id}'
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - 
        SubnetIds:
          - 
      Layers:
        - ''
